name: Cafe Manager CI/CD
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DATABASE_URL: sqlite:///task_manager.sqlite3
    steps:
      - uses: actions/checkout@v4
      - name: set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: 
          flake8 orders_manager
      - name: Run tests and generate coverage report with pytest
        run: |
          pytest orders_manager/orders/tests.py --ds=orders_manager.settings --cov=orders_manager --cov-branch --cov-report=xml -v
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: BogdanBarylo/test_task_orders
          files: ./coverage.xml
          fail_ci_if_error: true